"""A ratchet on notes that publish a number no producer regenerates.

THE FAILURE THAT PRODUCED IT, 2026-08-23. `docs/notes/band_excess_is_model_form.md`
publishes a regression table: profile height at +8.65 sigma, vapour density at
-0.75, the two correlating +0.415, over 79 traces. **No committed producer
computes any of it and no results/ row holds it.** The commit that introduced
the page says so in its own message, "Nothing in results/ moved", which was
written as a reassurance that no bound had changed and reads six days later as
the description of a gap.

WHY NO EXISTING GUARD SEES THIS. verify_results_fresh compares a CSV to its
producer. test_committed_csvs_still_match_their_producers does the same. Both
start from a results/ row, so a number that never became a row is outside the
domain of every freshness check in the repository. The docs tests read links,
images, structure and style, none of which is provenance. The number is
therefore published, public, and ungraded, and nothing in the tree could have
told anyone.

AND IT PROPAGATED INTO A GRADED FILE. On 2026-08-23 run_kernel_k8.py quoted
+8.65 and -0.75 into the note column of results/kernel_k8.csv, so a checked
file now carries unchecked numbers in prose that no check reads. That is the
same shape as the deferred-atlas falsehood found on the public page this
morning: a claim in a note column is prose no prose check reads.

WHY A RATCHET AND NOT AN ASSERTION. The blast radius was measured BEFORE this
file was written, which is the only reason it is not a blanket rule. 23 notes,
14 carrying numeric claims, and of those 4 cite no results/ file. Three of the
four are legitimate: two are DESIGN notes whose numbers are proposed
parameters rather than measurements, and one is the directory index quoting its
own children. A blanket assertion would have failed on three correct files and
been relaxed into uselessness by lunchtime. So this records a per-file budget
that can only fall, the mechanism test_prose_style_ratchet.py and
test_distribution_ratchet.py already run.

THE BUDGET IS NOW ZERO, and what it took to get there is the finding. Ten
notes were audited claim by claim against results/ and scripts/ on 2026-08-23.
**Seven of the ten turned out to have no producer for the numbers carrying
their own argument**, including one whose producer states in its own docstring
that it writes nothing, and one whose outcome factor had additionally been
hand-copied into the ledger generator as a literal and published in
docs/RESULTS.md. Three notes have a genuine results/ home and 109 individual
claims across the corpus remain unaccounted for INSIDE declared files, which
the declarations name rather than hide. A budget at zero therefore means every
note SAYS what it stands on, not that every number is graded.

THE ESCAPE, deliberately explicit. A note leaves the budget by declaring what
its numbers stand on, with the token `provenance:` and one of

    results/<name>.csv   the ledger row that holds them
    DESIGN               proposed parameters, not measurements of data
    PREREG               a rule fixed in advance, graded when the run happens
    INDEX                quoting its own children, which carry the standing
    NO_PRODUCER          computed once and regenerated by nothing, WITH A REASON

NO_PRODUCER is not an exemption and it is the point of the whole file. It costs
the author one visible sentence admitting the number is weaker than the ones
around it, which is exactly what a reader cannot otherwise tell. The band note
now carries it.

Run `python tests/test_note_provenance_ratchet.py --relax` after a genuine pass.
Raising a budget by hand means admitting a note got weaker.
"""
from __future__ import annotations

import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
NOTES = ROOT / "docs" / "notes"
BASELINE = Path(__file__).parent / "_note_provenance_baseline.json"

# A numeric CLAIM about data, not any number. Bare integers, dates, section
# numbers and MHz values are not claims; a sigma, a percentage and a bolded
# signed decimal are how this repository states a result.
CLAIM = re.compile(
    r"[-+]?\d+\.\d+\s*(?:sigma|per cent)"      # 8.65 sigma, 0.57 per cent
    r"|\*\*[-+]\d+\.\d+\*\*"                   # **+8.65** in a results table
    r"|\*\*[-+]?\d+\.\d+\s*(?:sigma|per cent)\*\*",
    re.I,
)

# The declaration, and it must name a kind. `provenance:` alone is not a
# declaration, which is the hole the distribution ratchet's own first version
# had when a status column was allowed to supply the reason.
KINDS = ("DESIGN", "PREREG", "INDEX", "NO_PRODUCER")
DECLARED = re.compile(
    r"provenance:\s*(?:`?(?:results/[A-Za-z0-9_./-]+\.csv)`?|" + "|".join(KINDS) + r")",
    re.I,
)


def _claims(text: str) -> int:
    return len(CLAIM.findall(text))


def _declared(text: str) -> bool:
    return bool(DECLARED.search(text))


def _undeclared_notes() -> dict[str, int]:
    """Notes that publish a numeric claim and declare nothing."""
    out = {}
    for p in sorted(NOTES.glob("*.md")):
        text = p.read_text()
        n = _claims(text)
        if n and not _declared(text):
            out[f"docs/notes/{p.name}"] = n
    return out


def test_no_note_publishes_a_new_undeclared_number():
    """Undeclared numeric claims may fall or hold, never rise."""
    baseline = json.loads(BASELINE.read_text())
    current = _undeclared_notes()

    worse = []
    for rel, now in sorted(current.items()):
        was = baseline.get(rel)
        if was is None:
            worse.append(f"{rel}: NEW note with {now} undeclared claims")
        elif now > was:
            worse.append(f"{rel}: {was} -> {now} (+{now - was})")

    assert not worse, (
        "a note published a number without saying what regenerates it. Add a "
        "`provenance:` line naming the results/ row, or DESIGN, PREREG, INDEX, "
        "or NO_PRODUCER with a reason. NO_PRODUCER is allowed and is not an "
        "exemption: it tells the reader the number is weaker than the ones "
        "beside it, which is the only thing they cannot work out for "
        "themselves.\n  " + "\n  ".join(worse)
        + "\n\nAfter a genuine pass, re-record with:"
          "\n  python tests/test_note_provenance_ratchet.py --relax")


def test_the_band_note_still_declares_no_producer():
    """The instance that produced this file does not silently lose its label.

    A ratchet counts what is missing. It cannot see a declaration being
    downgraded to a weaker true statement, and this particular declaration is
    the one a future editor is most likely to tidy away as unflattering.
    """
    text = (NOTES / "band_excess_is_model_form.md").read_text()
    assert re.search(r"provenance:\s*`?NO_PRODUCER", text), (
        "the band note dropped its NO_PRODUCER declaration. Its numbers are "
        "still regenerated by nothing. If a producer was written, point the "
        "declaration at the results/ row it now writes.")


def test_the_counter_separates_the_five_kinds(tmp_path):
    """The ceiling test: a guard that has only passed on valid inputs has not
    demonstrated that it detects its intended failure mode."""
    cases = {
        "bare.md": "The excess tracks height at 8.65 sigma.",
        "csv.md": "provenance: results/kernel_k8.csv\n\nHeight at 9.41 sigma.",
        "design.md": "provenance: DESIGN\n\nA block at 1.5 sigma costs 1200.",
        "noprod.md": "provenance: NO_PRODUCER, computed once\n\n+8.65 sigma.",
        "empty.md": "provenance:\n\nThe excess sits at 3.6 sigma.",
        "prose.md": "The window is 36 MHz wide and chapter 7 argues it.",
    }
    for name, body in cases.items():
        (tmp_path / name).write_text(body)

    assert _claims(cases["bare.md"]) == 1
    assert _claims(cases["prose.md"]) == 0, "a MHz span is not a claim"
    assert _declared(cases["csv.md"])
    assert _declared(cases["design.md"])
    assert _declared(cases["noprod.md"])
    assert not _declared(cases["bare.md"])
    # `provenance:` with no kind is NOT a declaration. The distribution
    # ratchet shipped this exact hole once, where a status column was allowed
    # to supply the reason, and the count fell silently.
    assert not _declared(cases["empty.md"]), "a bare token is not a declaration"


def test_a_declaration_that_wraps_a_line_is_still_seen(tmp_path):
    r"""The R_kernel phrase bank was blind to a phrase that WRAPPED a line and
    reported a clean sweep over a corpus that was not clean. That is the
    single most expensive blind spot this repository has found in a guard, so
    the wrapped case is pinned here rather than left to chance.

    This assertion was written the other way round first, asserting that a
    wrapped declaration is missed, on the theory that requiring the token to
    stay whole is simpler. The test failed on the day it was written, because
    `\s*` spans newlines and the counter had been right all along. The
    behaviour is kept and the assertion was corrected to match it: a guard
    that misses a wrapped declaration would charge an author for debt they had
    already declared, which is the same class of error in the opposite
    direction.
    """
    inline = "The table below (`provenance: NO_PRODUCER`, see the commit) shows\n+8.65 sigma."
    assert _declared(inline)
    wrapped = "The numbers carry `provenance:\nNO_PRODUCER` and stand at 8.65 sigma."
    assert _declared(wrapped), "a declaration split by a line break must still count"


def _relax() -> None:
    BASELINE.write_text(json.dumps(_undeclared_notes(), indent=2, sort_keys=True) + "\n")
    print(f"re-recorded {BASELINE.name}")


if __name__ == "__main__":
    if "--relax" in sys.argv:
        _relax()
    else:
        print(json.dumps(_undeclared_notes(), indent=2, sort_keys=True))
