"""A ratchet on notes that publish a number no producer regenerates.

THE FAILURE THAT PRODUCED IT, 2026-08-23. `docs/notes/band_excess_is_model_form.md`
publishes a regression table: profile height at +8.65 sigma, vapour density at
-0.75, the two correlating +0.415, over 79 traces. **No committed producer
computes any of it and no results/ row holds it.** The commit that introduced
the page says so in its own message, "Nothing in results/ moved", which was
written as a reassurance that no bound had changed and reads six days later as
the description of a gap.

WHY NO EXISTING GUARD SEES THIS. verify_results_fresh compares a CSV to its
producer. test_committed_csvs_still_match_their_producers does the same. Both
start from a results/ row, so a number that never became a row is outside the
domain of every freshness check in the repository. The docs tests read links,
images, structure and style, none of which is provenance. The number is
therefore published, public, and ungraded, and nothing in the tree could have
told anyone.

AND IT PROPAGATED INTO A GRADED FILE. On 2026-08-23 run_kernel_k8.py quoted
+8.65 and -0.75 into the note column of results/kernel_k8.csv, so a checked
file now carries unchecked numbers in prose that no check reads. That is the
same shape as the deferred-atlas falsehood found on the public page this
morning: a claim in a note column is prose no prose check reads.

WHY A RATCHET AND NOT AN ASSERTION. The blast radius was measured BEFORE this
file was written, which is the only reason it is not a blanket rule. 23 notes,
14 carrying numeric claims, and of those 4 cite no results/ file. Three of the
four are legitimate: two are DESIGN notes whose numbers are proposed
parameters rather than measurements, and one is the directory index quoting its
own children. A blanket assertion would have failed on three correct files and
been relaxed into uselessness by lunchtime. So this records a per-file budget
that can only fall, the mechanism test_prose_style_ratchet.py and
test_distribution_ratchet.py already run.

THE BUDGET IS NOW ZERO, and what it took to get there is the finding. Ten
notes were audited claim by claim against results/ and scripts/ on 2026-08-23.
**Seven of the ten turned out to have no producer for the numbers carrying
their own argument**, including one whose producer states in its own docstring
that it writes nothing, and one whose outcome factor had additionally been
hand-copied into the ledger generator as a literal and published in
docs/RESULTS.md. Three notes have a genuine results/ home and 109 individual
claims across the corpus remain unaccounted for INSIDE declared files, which
the declarations name rather than hide. A budget at zero therefore means every
note SAYS what it stands on, not that every number is graded.

THE ESCAPE, deliberately explicit. A note leaves the budget by declaring what
its numbers stand on, with the token `provenance:` and one of

    results/<name>.csv   the ledger row that holds them
    DESIGN               proposed parameters, not measurements of data
    PREREG               a rule fixed in advance, graded when the run happens
    INDEX                quoting its own children, which carry the standing
    NO_PRODUCER          computed once and regenerated by nothing, WITH A REASON

NO_PRODUCER is not an exemption and it is the point of the whole file. It costs
the author one visible sentence admitting the number is weaker than the ones
around it, which is exactly what a reader cannot otherwise tell. The band note
now carries it.

Run `python tests/test_note_provenance_ratchet.py --relax` after a genuine pass.
Raising a budget by hand means admitting a note got weaker.
"""
from __future__ import annotations

import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
NOTES = ROOT / "docs" / "notes"
BASELINE = Path(__file__).parent / "_note_provenance_baseline.json"

# A numeric CLAIM about data. WIDENED 2026-08-23, and the reason is the most
# important comment in this file.
#
# The first version matched only a decimal followed by "sigma" or "per cent",
# or a bolded signed decimal, on the theory that MHz values are not claims.
# **That was wrong and it made this guard report a clean corpus that was not
# clean.** Measured against the corpus: the narrow pattern saw claims on 14 of
# 23 notes and scored the undeclared budget at ZERO. The widened pattern sees
# claims on ALL 23 and finds NINE notes undeclared. On one page the narrow
# pattern counted 1 claim where an audit counted 16.
#
# So the budget of zero that this file recorded, and that docs/HISTORY.md
# published, was substantially an artefact of a detector that could not see
# most of the numbers. A guard's blind region matters more than its holes, and
# this one had been measured for coverage of FILES and never for coverage of
# NUMBERS WITHIN a file.
CLAIM = re.compile(
    r"(?<![\w.])[-+]?\d+(?:\.\d+)?\s*"
    r"(?:sigma|per cent|%|MHz|kHz|Hz|uK|mK|mW|W|mbar|nm|um|ms|counts?|dof)"
    r"|\*\*[-+]?\d+(?:\.\d+)?\*\*",
    re.I,
)

# The declaration, and it must name a kind. `provenance:` alone is not a
# declaration, which is the hole the distribution ratchet's own first version
# had when a status column was allowed to supply the reason.
KINDS = ("DESIGN", "PREREG", "INDEX", "NO_PRODUCER")
# A committed pure function is a LEGITIMATE and arguably stronger provenance
# than a CSV, because a function cannot go stale relative to itself. The
# vocabulary lacked it until 2026-08-23, and the cost of that gap was a FALSE
# declaration: docs/notes/vdw_difference_potential_and_4d_channel.md declared
# NO_PRODUCER while rb5s6s/vanderwaals.py::beta_self_anchored() reproduces its
# table exactly, verified by calling it. Faced with no correct option the
# author took the merely pessimistic one, which overstates the gap and so
# attracts no scrutiny. A GUARD WHOSE VOCABULARY CANNOT EXPRESS THE TRUTH WILL
# BE SATISFIED WITH SOMETHING FALSE.
CODE_REF = r"[A-Za-z0-9_./-]+\.py::[A-Za-z_][A-Za-z0-9_]*"
DECLARED = re.compile(
    r"provenance:\s*(?:`?(?:results/[A-Za-z0-9_./-]+\.csv)`?|`?(?:" + CODE_REF + r")`?|"
    + "|".join(KINDS) + r")",
    re.I,
)


def _claims(text: str) -> int:
    return len(CLAIM.findall(text))


def _declared(text: str) -> bool:
    return bool(DECLARED.search(text))


def _undeclared_notes() -> dict[str, int]:
    """Notes that publish a numeric claim and declare nothing."""
    out = {}
    for p in sorted(NOTES.glob("*.md")):
        text = p.read_text()
        n = _claims(text)
        if n and not _declared(text):
            out[f"docs/notes/{p.name}"] = n
    return out


def test_no_note_publishes_a_new_undeclared_number():
    """Undeclared numeric claims may fall or hold, never rise."""
    baseline = json.loads(BASELINE.read_text())
    current = _undeclared_notes()

    worse = []
    for rel, now in sorted(current.items()):
        was = baseline.get(rel)
        if was is None:
            worse.append(f"{rel}: NEW note with {now} undeclared claims")
        elif now > was:
            worse.append(f"{rel}: {was} -> {now} (+{now - was})")

    assert not worse, (
        "a note published a number without saying what regenerates it. Add a "
        "`provenance:` line naming the results/ row, or DESIGN, PREREG, INDEX, "
        "or NO_PRODUCER with a reason. NO_PRODUCER is allowed and is not an "
        "exemption: it tells the reader the number is weaker than the ones "
        "beside it, which is the only thing they cannot work out for "
        "themselves.\n  " + "\n  ".join(worse)
        + "\n\nAfter a genuine pass, re-record with:"
          "\n  python tests/test_note_provenance_ratchet.py --relax")


def test_the_band_note_still_declares_no_producer():
    """The instance that produced this file does not silently lose its label.

    A ratchet counts what is missing. It cannot see a declaration being
    downgraded to a weaker true statement, and this particular declaration is
    the one a future editor is most likely to tidy away as unflattering.
    """
    text = (NOTES / "band_excess_is_model_form.md").read_text()
    assert re.search(r"provenance:\s*`?NO_PRODUCER", text), (
        "the band note dropped its NO_PRODUCER declaration. Its numbers are "
        "still regenerated by nothing. If a producer was written, point the "
        "declaration at the results/ row it now writes.")


def test_the_counter_separates_the_five_kinds(tmp_path):
    """The ceiling test: a guard that has only passed on valid inputs has not
    demonstrated that it detects its intended failure mode."""
    cases = {
        "bare.md": "The excess tracks height at 8.65 sigma.",
        "csv.md": "provenance: results/kernel_k8.csv\n\nHeight at 9.41 sigma.",
        "design.md": "provenance: DESIGN\n\nA block at 1.5 sigma costs 1200.",
        "noprod.md": "provenance: NO_PRODUCER, computed once\n\n+8.65 sigma.",
        "empty.md": "provenance:\n\nThe excess sits at 3.6 sigma.",
        "prose.md": "The window is 36 MHz wide and chapter 7 argues it.",
    }
    for name, body in cases.items():
        (tmp_path / name).write_text(body)

    assert _claims(cases["bare.md"]) == 1
    # This assertion used to read `== 0, "a MHz span is not a claim"`, pinning
    # the belief that made the detector blind. Widening the pattern broke it,
    # which is the ceiling test doing its job: it held the old design in place
    # until the design was deliberately changed. A MHz value IS a claim, and
    # treating it as scenery is how a page carrying sixteen numbers scored one.
    assert _claims(cases["prose.md"]) == 1, "a MHz value is a claim"
    assert _declared(cases["csv.md"])
    assert _declared(cases["design.md"])
    assert _declared(cases["noprod.md"])
    assert not _declared(cases["bare.md"])
    # `provenance:` with no kind is NOT a declaration. The distribution
    # ratchet shipped this exact hole once, where a status column was allowed
    # to supply the reason, and the count fell silently.
    assert not _declared(cases["empty.md"]), "a bare token is not a declaration"


def test_a_declaration_that_wraps_a_line_is_still_seen(tmp_path):
    r"""The R_kernel phrase bank was blind to a phrase that WRAPPED a line and
    reported a clean sweep over a corpus that was not clean. That is the
    single most expensive blind spot this repository has found in a guard, so
    the wrapped case is pinned here rather than left to chance.

    This assertion was written the other way round first, asserting that a
    wrapped declaration is missed, on the theory that requiring the token to
    stay whole is simpler. The test failed on the day it was written, because
    `\s*` spans newlines and the counter had been right all along. The
    behaviour is kept and the assertion was corrected to match it: a guard
    that misses a wrapped declaration would charge an author for debt they had
    already declared, which is the same class of error in the opposite
    direction.
    """
    inline = "The table below (`provenance: NO_PRODUCER`, see the commit) shows\n+8.65 sigma."
    assert _declared(inline)
    wrapped = "The numbers carry `provenance:\nNO_PRODUCER` and stand at 8.65 sigma."
    assert _declared(wrapped), "a declaration split by a line break must still count"


def test_a_declared_target_must_actually_exist():
    """A declaration naming a results/ CSV or a function is graded as true
    forever unless something checks it against the filesystem.

    This was found by attacking the instrument rather than by using it: the
    regex matched the STRING and never asked whether the file was there, so
    `provenance: results/does_not_exist.csv` would have satisfied the ratchet
    permanently and at no cost. A lie that costs nothing to write and nothing
    to sustain is the one to expect.
    """
    missing = []
    for p in sorted(NOTES.glob("*.md")):
        text = p.read_text()
        for m in re.finditer(r"provenance:\s*`?(results/[A-Za-z0-9_./-]+\.csv)`?", text, re.I):
            if not (ROOT / m.group(1)).is_file():
                missing.append(f"{p.name} -> {m.group(1)} (no such file)")
        for m in re.finditer(r"provenance:\s*`?([A-Za-z0-9_./-]+\.py)::([A-Za-z_][A-Za-z0-9_]*)`?", text, re.I):
            mod, fn = m.group(1), m.group(2)
            if not (ROOT / mod).is_file():
                missing.append(f"{p.name} -> {mod} (no such file)")
            elif f"def {fn}" not in (ROOT / mod).read_text():
                missing.append(f"{p.name} -> {mod}::{fn} (no such function)")

    assert not missing, (
        "a note declares a provenance target that does not exist. The "
        "declaration is the whole escape hatch, so it has to name something "
        "real.\n  " + "\n  ".join(missing))


def test_the_claim_detector_sees_the_corpus_it_polices():
    """The detector must not be so narrow that a clean report is meaningless.

    This is the check the first version of this file lacked. Its blast radius
    was measured over FILES (how many notes owe a declaration) and never over
    NUMBERS WITHIN a file, so a pattern that saw one claim on a page carrying
    sixteen still reported a clean corpus. The threshold below is deliberately
    weak: it only asserts the detector is not blind on the pages that most
    obviously carry quantitative content.
    """
    seen = {p.name: _claims(p.read_text()) for p in NOTES.glob("*.md")}
    assert seen, "no notes found at all"
    blind = [n for n, c in seen.items() if c == 0]
    assert len(blind) <= 2, (
        "the claim detector finds no numbers on these notes, which is more "
        "likely a defect in the pattern than a property of the corpus:\n  "
        + "\n  ".join(sorted(blind)))


# --- the two falling budgets, added 2026-08-23 --------------------------------
BUDGETS = Path(__file__).parent / "_provenance_budgets.json"


def _csv_counts() -> dict:
    """The headline counts, read from the committed instrument.

    ONE-TIME REVALUATION, 2026-08-23. When the last nine undeclared notes were
    declared, two of these counts ROSE: notes_no_producer 6 to 7, because a
    note moved from invisible to visibly ungoverned, and orphan_claims_total
    105 to 182, because newly declared notes brought their own unaccounted
    counts into a total that had never seen them. **Neither rise is new debt.**
    The quantity that fell is notes_ungoverned_total, 15 to 7, which is why it
    exists. With notes_undeclared now at zero the other two are stable and can
    only fall from here, so the budgets were re-recorded once, deliberately,
    with this note rather than silently.
    """
    import csv as _csv
    out = {}
    p = ROOT / "results" / "unregenerated_claims.csv"
    for row in _csv.DictReader(p.open()):
        if row["quantity"] in ("notes_no_producer", "orphan_claims_total",
                               "orphans_on_reader_facing_surfaces",
                               "notes_undeclared", "notes_ungoverned_total"):
            out[row["quantity"]] = int(row["value"])
    return out


def test_the_provenance_debt_only_falls():
    """Two budgets that can only fall, the mechanism this repository already
    runs for prose, distributions, axes and note declarations.

    COUNTING the gap was done on 2026-08-23 and counting alone does not hold
    it. New work must not be able to add a note that rests on numbers nothing
    regenerates, nor add unaccounted claims to the notes already declared.
    Retirement happens when someone writes a producer or checks a claim into a
    row, and neither of those is a relabelling.
    """
    budgets = json.loads(BUDGETS.read_text())
    now = _csv_counts()

    worse = []
    for key, was in sorted(budgets.items()):
        is_now = now.get(key)
        if is_now is None:
            worse.append(f"{key}: no longer reported by the producer")
        elif is_now > was:
            worse.append(f"{key}: {was} -> {is_now} (+{is_now - was})")

    assert not worse, (
        "the provenance debt grew. A note may not newly rest on numbers no "
        "producer regenerates, and a declared note may not gain unaccounted "
        "claims. Write the producer, or check the claim into a row.\n  "
        + "\n  ".join(worse)
        + "\n\nAfter a genuine reduction, re-record with:"
          "\n  python tests/test_note_provenance_ratchet.py --relax-budgets")


def test_no_reader_facing_orphan_is_undisclosed():
    """The one class that is a release blocker.

    An ungoverned number confined to its own note is debt. The same number
    quoted on a page a reader acts on is a published claim with nothing behind
    it, and the partition in the producer counts exactly those. The budget
    holds that count, and the single current entry is disclosed at both of its
    printing sites.
    """
    budgets = json.loads(BUDGETS.read_text())
    now = _csv_counts()
    key = "orphans_on_reader_facing_surfaces"
    assert now.get(key, 99) <= budgets[key], (
        f"an ungoverned number reached a reader-facing surface: "
        f"{budgets[key]} allowed, {now.get(key)} found. Give it a producer or "
        f"disclose its standing where the page prints it.")


def test_the_budget_file_matches_the_instrument_today():
    """A budget recorded above the true count is a budget that permits growth
    silently, which is how a ratchet stops ratcheting."""
    budgets = json.loads(BUDGETS.read_text())
    now = _csv_counts()
    slack = {k: budgets[k] - now[k] for k in budgets if k in now and budgets[k] > now[k]}
    assert not slack, (
        "a budget sits above the current count, so the debt could grow back to "
        f"it unnoticed. Re-record: {slack}")


def test_the_instrument_does_not_eat_its_own_output(tmp_path):
    """Running the producer twice must give the same answer.

    It did not. The partition NAMES its reader-facing orphan in a note column,
    so the second run found that value inside unregenerated_claims.csv, counted
    it as present in results/, and reclassified it from orphan to quoted. The
    count moved 40 to 41 between runs and the CI freshness guard caught it.

    The principle behind the fix, which is worth more than the fix: a value
    appearing in the provenance instrument's own prose is not evidence that a
    producer regenerates it. SELF-REFERENCE IS NOT PROVENANCE. Any instrument
    that both writes into results/ and reads results/ to make a judgement can
    fail this way, so the check is the general one, idempotency, rather than a
    test for the one value.
    """
    import csv as _csv
    import shutil
    import subprocess
    import sys

    out = ROOT / "results" / "unregenerated_claims.csv"
    if not out.is_file():
        return
    backup = tmp_path / "before.csv"
    shutil.copy2(out, backup)

    def _partition_rows():
        return {r["quantity"]: r["value"] for r in _csv.DictReader(out.open())
                if r["scope"] == "PARTITION"}

    try:
        first = _partition_rows()
        r = subprocess.run([sys.executable, "scripts/run_unregenerated_claims.py"],
                           cwd=ROOT, capture_output=True, text=True)
        assert r.returncode == 0, r.stderr[-400:]
        second = _partition_rows()
        assert first == second, (
            "the producer gives a different answer on a second run, so it is "
            f"reading something it wrote:\n  before {first}\n  after  {second}")
    finally:
        shutil.copy2(backup, out)


def _relax() -> None:
    BASELINE.write_text(json.dumps(_undeclared_notes(), indent=2, sort_keys=True) + "\n")
    print(f"re-recorded {BASELINE.name}")


if __name__ == "__main__":
    if "--relax-budgets" in sys.argv:
        BUDGETS.write_text(json.dumps(_csv_counts(), indent=2, sort_keys=True) + "\n")
        print(f"re-recorded {BUDGETS.name}")
    elif "--relax" in sys.argv:
        _relax()
    else:
        print(json.dumps(_undeclared_notes(), indent=2, sort_keys=True))
