#!/usr/bin/env python
"""What a new campaign yields: vapour cell alone, against cell plus nanofibre.

Run THROUGH THE TWIN. Every number here is the median of the fit's own
reported uncertainty across independent synthetic datasets, generated by the
same forward model this package fits real data with and fitted back by the
same fitter, so it is what the real analysis would report rather than a
linearised bound.

WHY THE COMPARISON AXIS IS NOT Delta_alpha. An earlier version of this
forecast compared the two arms on Delta_alpha alone, because Delta_alpha is
the only quantity that transports between apparatuses. The owner refuted the
framing: transportability is the rule for COMPARING BOUNDS ACROSS
APPARATUSES, and this is a DESIGN question. Judged on Delta_alpha the fibre
looks like a worse cell. Judged on what it identifies, it is a different
instrument, and the case is that it REMOVES degeneracies the cell can only
fight.

THE TWO DEGENERACIES THAT LIMIT THE CELL NOW.
  1. Collisional against residual Gaussian, fitted correlation about -0.9.
  2. Transit against residual Gaussian, which runs through the beam waist,
     the record's largest open systematic, bounded below at 38 um with no
     upper bound from the data at all.

WHAT THE FIBRE DOES TO EACH, and the second is not an improvement but a
change of kind. Collisions essentially leave the budget at MOT density. The
waist is replaced by a fibre diameter, which is measurable, and a mode that
`rb5s6s.fibre.solve_he11` computes from it.

AND THE COST, WHICH IS REAL AND IS MODELLED HERE. The fibre's transit kernel
is NEAR-Lorentzian, so it adds very nearly to the natural and collisional
widths and has almost no separate existence at a single temperature. This
producer folds the fibre transit into the Lorentzian core rather than
pretending the cusp survives.

THE WORD WAS "LORENTZIAN" FLATLY UNTIL 2026-08-28, and here that was not a
docstring matter: the line `lorentzian_excess = mean_transit + gamma_coll` is a
LINEAR SUM, and a linear sum of widths is exact only for Lorentzians. The
kernel is a squared Lorentzian averaged over the Maxwell distribution, so the
sum is an approximation whose error this producer does not characterise.

Two things are worth separating. The SIZE of the transit term moved by a factor
between 2.3 and 4.1 and that is carried through `transit_fwhm`. The ADDITIVITY
is an approximation that survives because the ladder argument rests on the
sqrt(T) scaling and not on exact additivity, so the design is unaffected and
the wording was wrong. Only a temperature ladder separates them, and
whether it does is `results/fibre_twin.csv`, not this file.

ACQUISITION REALISM IS NOT ASSUMED EQUAL. The cell reaches a noise fraction
of about 0.004 of peak on a scope trace in seconds. The fibre is photon
counting at a committed 25 to 40 counts per ms, so the same fractional
precision costs integration time, and this producer reports the time rather
than hiding it.
"""
from __future__ import annotations

import csv
from pathlib import Path

from rb5s6s.cooperative import IONISATION_LIMIT_CM
from rb5s6s.fibre import solve_he11, transit_fwhm
from rb5s6s.forecast import forecast_precision
from rb5s6s.polarizability import E_6S_CM

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"

# Committed acquisition realism and truth, read rather than retyped.
REALISM = RESULTS / "twin_realism.csv"
ONF = RESULTS / "onf_candidate.csv"

# 200 Monte-Carlo datasets per configuration since 2026-08-31; the first
# committed version ran 24, and its rows carried no spread, which the
# chapter's section 7 listed as a caveat. The spread rows retire it: each
# precision row gains a sibling *_spread row, the standard deviation of
# the per-dataset reported errors, so a reader can see how much the
# median moves between synthetic campaigns. Computation was the only
# reason for 24, and computation is not rationed any more.
N_TRIALS = 200
CELL_NOISE = 0.004     # fraction of peak, the archive's working value
ONF_COUNTS_PER_MS = 30.0   # centre of the committed 25 to 40 band
ONF_DIAMETER_NM = 370.0    # raj2026's fibre, the one a campaign would use
PROBE_NM = 993.4181        # the literature line, never the wavemeter label
DIAMETER_TOL_NM = 20.0     # assumed, matching run_guided_mode_tables
MOT_T_K = 150e-6           # the molasses temperature the arm assumes


def _read(path: Path, kcol: str, vcol: str, filt=None) -> dict:
    out = {}
    with open(path, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            if filt and not filt(row):
                continue
            out[row[kcol]] = row[vcol]
    return out


def _band(text: str) -> tuple:
    lo, hi = (p.strip() for p in text.split(" to "))
    return float(lo), float(hi)


from _producer_lock import take_producer_lock     # noqa: E402


def main() -> None:
    take_producer_lock("run_campaign_twin_forecast")
    truth_rows = _read(REALISM, "quantity", "value",
                       filt=lambda r: r["scope"] == "TRUTH")
    onf = _read(ONF, "quantity", "value")

    g_cell = float(truth_rows["gamma_coll_mhz"])
    s_cell = float(truth_rows["sigma_laser_mhz"])
    t_cell = float(truth_rows["transit_fwhm_mhz"])

    rows = []

    def add(arm, quantity, value, unit, basis, note, status):
        rows.append(dict(arm=arm, quantity=quantity, value=value, unit=unit,
                         basis=basis, note=note, status=status))

    # ---------------- the cell arm, through the twin ----------------------
    cell_design = {"span_mhz": 120.0, "n_points": 2000, "noise": CELL_NOISE,
                   "amp": 1.0, "T_C": 130.0}
    cell_truth = {"gamma_coll": g_cell, "sigma_laser": s_cell,
                  "transit_fwhm": t_cell}

    for n_traces, label in ((5, "5 traces"), (20, "20 traces"),
                            (80, "80 traces")):
        d = dict(cell_design, n_traces=n_traces)
        out = forecast_precision(cell_truth, d, n_trials=N_TRIALS,
                                 scalings=False, return_trials=True)
        import numpy as _np
        spread = float(_np.std(out["gamma_coll_err_trials"], ddof=1))
        add("cell", f"gamma_coll_{n_traces}traces_err",
            round(out["gamma_coll_err"], 5), "MHz",
            label, "median of the fit's own reported error over "
            f"{N_TRIALS} synthetic datasets", "ENVELOPE")
        add("cell", f"gamma_coll_{n_traces}traces_err_spread",
            round(spread, 5), "MHz", label,
            "standard deviation of the reported error across the "
            f"{N_TRIALS} datasets, the sibling row the chapter's caveat "
            "asked for", "DIAGNOSTIC")
        add("cell", f"sigma_laser_{n_traces}traces_err",
            round(out["sigma_laser_err"], 5), "MHz",
            label, "the residual Gaussian, not a laser linewidth", "ENVELOPE")
        add("cell", f"corr_laser_coll_{n_traces}traces",
            round(out["corr_laser_coll"], 4),
            "correlation", label,
            "THE CELL'S FIRST DEGENERACY, measured by the twin rather than "
            "asserted. Near -1 means the two widths trade off and the split "
            "is not identified", "DIAGNOSTIC")

    # ---------------- the fibre arm, through the same twin ----------------
    mode = solve_he11(ONF_DIAMETER_NM, PROBE_NM)
    add("onf", "neff", round(mode.neff, 5), "index",
        f"HE11 solve, {ONF_DIAMETER_NM:.0f} nm fibre at {PROBE_NM} nm",
        "SOLVED, replacing the assumed neff_band 1.08 to 1.25 which "
        "corresponds to 485 to 796 nm fibres and does not contain this one",
        "CALIB")
    add("onf", "amplitude_decay_length", round(mode.amplitude_decay_nm, 1),
        "nm", "1/q from the same solve",
        "AMPLITUDE convention, the same one the committed "
        "evanescent_decay_length band carries. That band read 211 to 388 nm "
        "while it was an assumed index range and did not contain this value. "
        "The producer now computes it from the solve and it does",
        "CALIB")

    # COMPUTED ON THIS FILE'S OWN FIBRE, not read from another's.
    #
    # This read `transit_onf_cold_band` from results/onf_candidate.csv, which
    # is computed on a 400 nm fibre, into an arm whose every other row is the
    # 370 nm one. The band is 73.5 to 99.0 kHz on the 400 nm fibre and 54.8 to
    # 79.9 on the 370 nm, so the published lorentzian_excess_truth ran 1.28x
    # high for the apparatus the row names.
    #
    # THE SIBLING PRODUCER CARRIES TWENTY-FIVE LINES ABOUT THIS EXACT CLASS,
    # written earlier in the same wave, and the class was fixed there and not
    # here. That is the sixth instance of a repair landing at one site of a
    # class and not its siblings, and it is why the comment names the class
    # rather than only the fix.
    _tl = solve_he11(ONF_DIAMETER_NM + DIAMETER_TOL_NM, PROBE_NM).intensity_decay_nm
    _th = solve_he11(ONF_DIAMETER_NM - DIAMETER_TOL_NM, PROBE_NM).intensity_decay_nm
    t_onf_lo, t_onf_hi = sorted(
        transit_fwhm(MOT_T_K, x * 1e-9).fwhm_hz / 1e3 for x in (_tl, _th))
    g_onf = float(onf["gamma_coll_at_MOT_density"]) / 1e6      # Hz -> MHz

    # The fibre transit is NEAR-Lorentzian, so it adds to the Lorentzian core
    # to a good approximation and is not a separate kernel. This sum is exact
    # only for true Lorentzians and the kernel is a Maxwell-averaged squared
    # Lorentzian, so the linear addition is an approximation, not an identity.
    lorentzian_excess = (0.5 * (t_onf_lo + t_onf_hi)) / 1e3 + g_onf
    add("onf", "lorentzian_excess_truth", round(lorentzian_excess, 5), "MHz",
        "mean fibre transit plus collisional at MOT density",
        "the fibre's whole non-natural Lorentzian budget, summed linearly. "
        "Its parts have almost no separate existence at one temperature, "
        "which is the cost the fibre pays for removing the cell's "
        "degeneracies. The sum is exact for Lorentzians and the transit "
        "kernel is a Maxwell-averaged squared Lorentzian, so this is an "
        "approximation whose error is not characterised here",
        "ENVELOPE")

    # Acquisition: photon counting, so a target fractional noise costs time.
    for frac, label in ((0.02, "noise 0.02"), (0.004, "noise 0.004")):
        counts_needed = 1.0 / (frac ** 2)
        ms_per_point = counts_needed / ONF_COUNTS_PER_MS
        minutes = ms_per_point * 2000 / 1000.0 / 60.0
        # AN UNCERTAINTY EXISTS HERE AND WAS SEEDED AS DEBT INSTEAD.
        # ONF_COUNTS_PER_MS is the CENTRE of the committed 25 to 40 band that
        # rajasree2020spin measured on this transition, and minutes go as
        # 1/rate, so the band propagates directly. A row whose uncertainty is
        # one division away is not debt, it is an omission, and protocol
        # 8a.1 asks for the number or a stated reason there is none.
        lo = counts_needed / 40.0 * 2000 / 1000.0 / 60.0
        hi = counts_needed / 25.0 * 2000 / 1000.0 / 60.0
        add("onf", f"minutes_per_trace_{frac:g}_err", round((hi - lo) / 2, 2),
            "minutes", label,
            "half-span of the committed 25 to 40 counts per ms band, which "
            "is the dominant uncertainty here because minutes go as one over "
            "the rate", "ENVELOPE")
        add("onf", f"minutes_per_trace_{frac:g}", round(minutes, 2),
            "minutes", label,
            f"shot noise at {ONF_COUNTS_PER_MS:.0f} counts per ms over 2000 "
            "points. THE FIBRE'S REAL COST IS TIME, and the cell reaches "
            "0.004 in seconds",
            "ENVELOPE")

        onf_truth = {"gamma_coll": lorentzian_excess,
                     "sigma_laser": s_cell,
                     "transit_fwhm": 1e-4}
        d = dict(span_mhz=60.0, n_points=2000, n_traces=5, noise=frac,
                 amp=1.0, T_C=25.0)
        out = forecast_precision(onf_truth, d, n_trials=N_TRIALS,
                                 scalings=False)
        add("onf", f"lorentzian_excess_{frac:g}_err",
            round(out["gamma_coll_err"], 5), "MHz", label,
            "error on the TOTAL Lorentzian excess, which is what a fibre line "
            "at one temperature can report", "ENVELOPE")
        add("onf", f"sigma_laser_{frac:g}_err",
            round(out["sigma_laser_err"], 5), "MHz",
            label, "the Gaussian residual, testable here because a guided "
            "mode has no free-space retro to tilt", "ENVELOPE")
        add("onf", f"corr_laser_coll_{frac:g}",
            round(out["corr_laser_coll"], 4),
            "correlation", label,
            "the fibre's own degeneracy between its Lorentzian total and the "
            "Gaussian, to be read against the cell's", "DIAGNOSTIC")

    # ---------------- what changes between the arms -----------------------
    add("comparison", "collisional_budget_ratio",
        round(g_cell / g_onf, 1), "factor",
        "committed cell gamma_coll over gamma_coll at MOT density",
        "the collisional channel essentially leaves the budget. This is the "
        "cell contribution the fibre removes. It does NOT remove the "
        "Lorentzian-against-Gaussian correlation, which the twin measures at "
        "about -0.94 in BOTH arms",
        "DIAGNOSTIC")
    add("comparison", "geometry_parameter",
        "waist assumed to diameter measured", "kind",
        "w0 has no upper bound from the cell data. a fibre diameter is an "
        "SEM or mode-cutoff measurement",
        "A CHANGE OF KIND, not a smaller uncertainty, and the reason the "
        "arms are not two versions of one measurement",
        "DIAGNOSTIC")

    # ---- the probe cannot drive the mechanism the ONF group diagnosed -----
    # Carried here from a run_campaign_forecast.py that was DRAFTED AND
    # WITHDRAWN inside this same uncommitted wave, whose Delta_alpha framing
    # the owner refused. It is in no commit, so "retired" was an unverifiable
    # history claim in permanent source and is not what happened. README and
    # docs/plan/02_priorities.md both assert this exclusion and neither had a
    # producer behind it.
    CM_PER_EV = 8065.54429
    photon_ev = 1239.84193 / (2e7 / E_6S_CM)      # the LITERATURE line
    need_ev = (IONISATION_LIMIT_CM - E_6S_CM) / CM_PER_EV
    add("model", "photoionisation_margin_from_6S", round(need_ev - photon_ev, 4),
        "eV",
        f"ionisation limit {IONISATION_LIMIT_CM} cm-1 minus the committed "
        f"E_6S_CM {E_6S_CM:.2f} cm-1, minus the literature-line photon",
        "positive means SINGLE-photon ionisation from 6S is excluded at the "
        "probe wavelength. TWO-photon ionisation from 6S is energetically "
        "OPEN and no committed row bounds its rate, so no claim that this probe "
        "cannot "
        "ionise rests on this margin alone. What does survive is that a 5S-6S "
        "probe populates no Rydberg state, so the Rydberg-ground collisional "
        "ionisation raj2026 identifies is absent by construction",
        "CALIB")

    out_path = RESULTS / "campaign_twin_forecast.csv"
    with open(out_path, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=["arm", "quantity", "value", "unit",
                                           "basis", "note", "status"])
        w.writeheader()
        w.writerows(rows)
    print(f"wrote {out_path} ({len(rows)} rows)")
    for r in rows:
        print(f"  {r['arm']:<11} {r['quantity']:<26} {str(r['value']):>12} "
              f"{r['unit']:<12} {r['basis']}")


if __name__ == "__main__":
    main()
